trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  acrName: milanacr2026
  acrLoginServer: milanacr2026.azurecr.io
  imageName: hotel-app
  imageTag: $(Build.BuildId)
  fullImage: milanacr2026.azurecr.io/hotel-app:latest

stages:

# =========================
# BUILD & PUSH TO ACR
# =========================
- stage: Build
  displayName: Build and Push Docker Image
  jobs:

  - job: BuildPush
    displayName: Build & Push
    steps:

    # Login to Azure
    - task: AzureCLI@2
      displayName: Login to Azure & ACR
      inputs:
        azureSubscription: 'app-hotel-coonection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(acrName)

    # Build Image
    - script: |
        docker build -t $(acrLoginServer)/$(imageName):latest .
      displayName: Build Docker Image

    # Push Image
    - script: |
        docker push $(acrLoginServer)/$(imageName):latest
      displayName: Push Docker Image


# =========================
# TRIGGER VM DEPLOYMENT (NO SSH)
# =========================
- stage: Deploy
  displayName: Deploy on VM (No SSH)
  dependsOn: Build

  jobs:
  - job: TriggerDeploy
    displayName: Trigger systemd deployment
    steps:

    - task: AzureCLI@2
      displayName: Restart deployment on VM via Azure
      inputs:
        azureSubscription: 'app-hotel-coonection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Triggering VM deployment..."

          # Run deployment locally on VM using VM Run Command (NO SSH)
          az vm run-command invoke \
            --resource-group app-test-dev-rg \
            --name hotel-dev-vm \
            --command-id RunShellScript \
            --scripts "
              systemctl restart hotel-app.service
            "