trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  acrName: milanacr2026
  acrLoginServer: milanacr2026.azurecr.io
  imageName: hotel-app
  imageTag: $(Build.BuildId)

stages:

# =========================
# BUILD & PUSH TO ACR
# =========================
- stage: Build
  displayName: Build and Push Docker Image

  jobs:

  - job: BuildPush
    displayName: Build & Push

    steps:

    # Login to Azure & ACR
    - task: AzureCLI@2
      displayName: Login to Azure & ACR
      inputs:
        azureSubscription: 'app-hotel-coonection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(acrName)

    # Build Image
    - script: |
        docker build -t $(acrLoginServer)/$(imageName):$(imageTag) .
      displayName: Build Docker Image

    # Push Image
    - script: |
        docker push $(acrLoginServer)/$(imageName):$(imageTag)
      displayName: Push Docker Image


# =========================
# DEPLOY TO AKS
# =========================
- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build

  jobs:

  - job: DeployAKS
    displayName: Deploy Latest Image To AKS

    steps:

    - task: AzureCLI@2
      displayName: Connect to AKS and Deploy
      inputs:
        azureSubscription: 'app-hotel-coonection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |

          echo "Connecting to AKS..."

          az aks get-credentials \
            --resource-group app-test-dev-rg \
            --name hotel-aks \
            --overwrite-existing

          echo "Updating deployment image..."

          kubectl set image deployment/hotel-app \
            hotel-app=$(acrLoginServer)/$(imageName):$(imageTag)

          echo "Waiting for rollout..."

          kubectl rollout status deployment/hotel-app --timeout=300s

          echo "Deployment completed successfully"

          kubectl get pods -o wide